version: '3.8'

services:
  electrumx:
    image: ghcr.io/red-coracle/electrumx:latest
    ports:
      - 50002:50002
      - 50004:50004
    volumes:
      - /path/to/storage/electrum:/data
    environment:
      - EVENT_LOOP_POLICY=uvloop
      - LOG_SESSIONS=600
      - DB_ENGINE=rocksdb
      - COIN=Bitcoin
      - DROP_CLIENT_UNKNOWN=1
      - DAEMON_URL=http://username:password@123.456.789.10:8332/
